name: Changelogs

concurrency:
  group: changelogs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches: [ arumoon-server ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Publish changelog
      run: echo test
